### PR TITLE
Navbar Feature

### PR DESCRIPTION
**Pull request by imireallan**
I have attached a static navbar on all the pages, and also I have downgraded the version of bootstrap from version 4 to 3. I have modified the css for the login and registration form

### CODE REVIEW

**Comment by imireallan** [comment]
I downgraded because some of the classes defined in bootstrap 3 were not working on version 4. Some of the class that I had challenges were navbar and also the pull-left and pull-right classes.
On the wireframes kindly explain what you mean by hosting on the Github pages

**Comment by SrMoffat** [comment]
I think the navbar and pull-right classes of Bootstrap 4 work just fine because I have used them. Maybe there was something wrong with the Bootstrap js...you can check the <link> tags and the <script> tags at the bottom to see if the js and jquery have been appropriately referenced. Even so, there is no big difference between version 3 and 4. For Github pages visit https://pages.github.com/ and read more on how to host your UI.

**Comment by imireallan** [comment]
I will look into those two versions. On the wireframes and UML class diagrams can you comment on those and clarify on some issues you might find

**Comment by imireallan** [comment]
Am following the Andela Shopping List challenge and so far I havent seen anything on github pages. The guidelines were to host the wireframes and UML class diagram on the designs folder. I will research more on github pages. Thanks  for the heads up

**Comment by SrMoffat** [comment]
When you look at a recent challenge like (Bright Events), you will realize that the Andela team also requires you to host your UI pages on Github Pages. Given that the challenge I more recent than Bucket List then maybe you should consider and read through Github Pages when you have time. Other than that, everything seems to be fine. Let me review the UML diagram.

**Comment by imireallan** [comment]
Nyc. Kindly share the Bright Events challenge

**Comment by SrMoffat** [comment]
[Bright Events( Public Version) (2).docx](https://github.com/imireallan/Bucketlist-API/files/1766150/Bright.Events.Public.Version.2.docx)

Have a look at it. I would suggest we start working on this together for easier collaboration for two reasons:
It is more recent than bucket list
It includes explicit specifications for the API required
It will allow us to exchange ideas since we will be working on the same thing. 

You call. 
Then once done with the changes in this pull request make sure you "merge with master" then start a new branch

**Comment by imireallan** [comment]
Yea we should work on that challenge together.I havent done anything Pivotal Tracker, so you will guide me there. Let me first merge this branch and continue with the challenge. I will buzz you wen am ready for the Bright Events Challenge. Let me walk through it first

**Comment by imireallan** [comment]
Yea we should work on that challenge together.I havent done anything Pivotal Tracker, so you will guide me there. Let me first merge this branch and continue with the challenge. I will buzz you wen am ready for the Bright Events Challenge. Let me walk through it first

**Comment by SrMoffat** [comment]
Cool bro. 

Let me know when you are ready.

**Pull request merged**
